# -*- mode: ruby -*-
# vi: set ft=ruby :

sshportPoint="10"
current_dir = File.dirname(File.expand_path(__FILE__))
Vagrant.configure("2") do |vmconf|
  vmconf.vm.box = "centos/7"
  vmconf.vm.define "anssrv" do |ansconfig|
    ansconfig.vm.network :private_network, ip: "10.1.43.100"
    ansconfig.vm.hostname = "anssrv"
    ansconfig.ssh.forward_agent = true
    ansconfig.vm.network :forwarded_port, guest: 22, host: "#{sshportPoint}10", id: "ssh"
    ansconfig.vm.provider :virtualbox do |v1|
      v1.customize ["modifyvm", :id, "--memory", 1024]
      v1.customize ["modifyvm", :id, "--name", "anssrv"]  
    end
    ansconfig.vm.provision "shell", path: "scripts/install.sh"
    ansconfig.vm.provision :reload
    ansconfig.vm.provision "shell", path: "scripts/devopstools.sh"
  end
  (1..3).each do |i|
     vmconf.vm.define "centos#{i}" do |centosconfig|
       centosconfig.vm.network :private_network, ip: "10.1.43.1#{i}"
       centosconfig.vm.hostname = "centos#{i}"
       centosconfig.ssh.forward_agent = true
       centosconfig.vm.network :forwarded_port, guest: 22, host: "#{sshportPoint}1#{i}", id: "ssh"
       centosconfig.vm.provider :virtualbox do |v1|
         v1.customize ["modifyvm", :id, "--memory", 1024]
         v1.customize ["modifyvm", :id, "--name", "centos#{i}"]
       end
       centosconfig.vm.provision "shell", path: "scripts/install.sh"
       centosconfig.vm.provision :reload
       #centosconfig.vm.provision "shell", path: "scripts/centosconfig1.sh", args: ip
     end
  end
  (1..3).each do |i|
     vmconf.vm.define "ubuntu#{i}" do |ubuntuconfig|
       ubuntuconfig.vm.box = "ubuntu/bionic64"
       ubuntuconfig.vm.network :private_network, ip: "10.1.43.2#{i}"
       ubuntuconfig.vm.hostname = "ubuntu#{i}"
       ubuntuconfig.ssh.forward_agent = true
       ubuntuconfig.vm.network :forwarded_port, guest: 22, host: "#{sshportPoint}2#{i}", id: "ssh"
       ubuntuconfig.vm.provider :virtualbox do |v1|
         v1.customize ["modifyvm", :id, "--memory", 1024]
         v1.customize ["modifyvm", :id, "--name", "ubuntu#{i}"]
       end
       ubuntuconfig.vm.provision "shell", path: "scripts/install.sh"
       #ubuntuconfig.vm.provision "shell", path: "scripts/centosconfig.sh", args: "#{i}"
       ubuntuconfig.vm.provision :reload
     end
  end
end
