# -*- mode: ruby -*-
# vi: set ft=ruby :

kubemasterIP = "172.18.8.10"
home = '/home/vagrant'
user = 'vagrant'
$count = 3
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.provider 'virtualbox' do |vb|
   vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
  end
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.define "kubemaster" do |kubemaster|
    kubemaster.vm.box = "centos/7"
    kubemaster.vm.hostname = "kubemaster"
    kubemaster.vm.network "private_network", ip: kubemasterIP
    kubemaster.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = 4
      vb.name = "kubemaster"
    end
    kubemaster.vm.provision "shell", path: "scripts/install.sh"
    kubemaster.vm.provision "shell", path: "scripts/kubemasterinstall.sh", args: [kubemasterIP, home, user]
  end
  (1..$count).each do |i|
    config.vm.define "kubenode#{i}" do |kubenode|
      kubenode.vm.box = "centos/7"
      kubenode.vm.hostname = "kubenode#{i}"
      ip = "172.18.8.#{i+100}"
      kubenode.vm.network "private_network", ip: ip
      kubenode.vm.provider "virtualbox" do |vb|
        vb.memory = "2560"
        vb.cpus = 2
        vb.name = "kubenode#{i}"
      end
      kubenode.vm.provision "shell", path: "scripts/install.sh"
      kubenode.vm.provision "shell", path: "scripts/kubenodeinstall.sh"
    end
  end
end
