apiVersion: v1
kind: Pod
metadata:
  name: gluster-pod
  labels:
    name: gluster-pod
spec:
  containers:
  - name: gluster-pod
    image: busybox
    command: ["sleep", "60000"]
    volumeMounts:
    - name: gluster-vol
      mountPath: /usr/share/busybox
      readOnly: false
  volumes:
  - name: gluster-vol
    persistentVolumeClaim:
      claimName: gluster-pvc

