# -*- mode: ruby -*-
# vi: set ft=ruby :

sshportPoint = "200"
mysqlIP = "10.1.200.100"
keycloakUserDB = "keycloak"
keycloakPass = "Keycloak123_"
mysqlConVer='14'

Vagrant.configure("2") do |config|
  config.vm.define "mysqlsrv" do |mysqlcnf|
    mysqlcnf.vm.hostname = "mysqlsrv"
    mysqlcnf.vm.box = "centos/7"
    mysqlcnf.vm.network "private_network", ip: "#{mysqlIP}"
    mysqlcnf.ssh.forward_agent = true  
    mysqlcnf.vm.network :forwarded_port, guest: 22, host: "#{sshportPoint}32", id: "ssh"
    mysqlcnf.vm.provider :virtualbox do |v1|
      v1.customize ["modifyvm", :id, "--memory", 1024]
      v1.customize ["modifyvm", :id, "--cpus", 1]
      v1.customize ["modifyvm", :id, "--name", "mysqlsrv"]
    end
    mysqlcnf.vm.provision "shell", path: "scripts/install.sh"
    mysqlcnf.vm.provision :reload 
    mysqlcnf.vm.provision "shell", path: "scripts/mysqlinstall.sh", args: "#{mysqlIP} #{keycloakUserDB} #{keycloakPass}"
  end

  (1..2).each do |i|
     config.vm.define "keycloak#{i}" do |keycloak|
       keycloak.vm.box = "centos/7"
       keycloak.vm.network :private_network, ip: "10.1.200.4#{i}"
       keycloak.vm.hostname = "keycloak#{i}"
       keycloak.ssh.forward_agent = true
       keycloak.vm.network :forwarded_port, guest: 22, host: "#{sshportPoint}8#{i}", id: "ssh"
       keycloak.vm.provider :virtualbox do |v1|
         v1.customize ["modifyvm", :id, "--memory", 1024]
         v1.customize ["modifyvm", :id, "--name", "keycloak#{i}"]
       end
       keycloak.vm.provision "shell", path: "scripts/install.sh"
       keycloak.vm.provision :reload 
       keycloak.vm.provision "shell", path: "scripts/keycloak-install.sh", args: "#{mysqlIP} #{keycloakUserDB} #{keycloakPass} 10.1.200.4#{i} #{mysqlConVer}"
     end
  end
end
