# -*- mode: ruby -*-
# vi: set ft=ruby :

sshportPoint = "200"
current_dir = File.dirname(File.expand_path(__FILE__))
consulDomain = "consul.epam.com"
nomadVersion="0.8.6"
Vagrant.configure("2") do |nomadserver|
  require './vagrant-provision-reboot-plugin'
  nomadserver.vm.box = "centos/7"
  (1..3).each do |i|
     nomadserver.vm.define "nomadsrv#{i}" do |nomadsrv|
       nomadsrv.vm.network :private_network, ip: "10.1.42.10#{i}"
       nomadsrv.vm.hostname = "nomadconsulsrv#{i}"
       nomadsrv.ssh.forward_agent = true
       nomadsrv.vm.network :forwarded_port, guest: 22, host: "#{sshportPoint}1#{i}", id: "ssh"
       nomadsrv.vm.provider :virtualbox do |v1|
         v1.customize ["modifyvm", :id, "--memory", 2048]
         v1.customize ["modifyvm", :id, "--name", "nomadconsulsrv#{i}"]  
       end
       nomadsrv.vm.provision "shell", path: "scripts/install.sh", args: "consul vault"
       nomadsrv.vm.provision :unix_reboot
       nomadsrv.vm.provision "shell", path: "scripts/consulservers.sh", args: "10.1.42.10#{i} consul"
       nomadsrv.vm.provision "shell", path: "scripts/nomadservers.sh", args: "10.1.42.10#{i} nomad #{nomadVersion}"
     end
  end
  (1..2).each do |i|
     nomadserver.vm.define "nomadagent#{i}" do |nomadagent|
       nomadagent.vm.network :private_network, ip: "10.1.42.20#{i}"
       nomadagent.vm.hostname = "nomadconsulagent#{i}"
       nomadagent.ssh.forward_agent = true
       nomadagent.vm.network :forwarded_port, guest: 22, host: "#{sshportPoint}2#{i}", id: "ssh"
       nomadagent.vm.provider :virtualbox do |v1|
         v1.customize ["modifyvm", :id, "--memory", 1024]
         v1.customize ["modifyvm", :id, "--name", "nomadconsulagent#{i}"]  
       end
       nomadagent.vm.provision "shell", path: "scripts/install.sh", args: "consul vault" 
       nomadagent.vm.provision :unix_reboot
       nomadagent.vm.provision "shell", path: "scripts/consulclients.sh", args: "10.1.42.20#{i} consul"
       nomadagent.vm.provision "shell", path: "scripts/vaultconfigure.sh", args: "10.1.42.20#{i} vault #{consulDomain}"
       nomadagent.vm.provision "shell", path: "scripts/nomadservers.sh", args: "10.1.42.20#{i} nomad #{nomadVersion}"
     end
  end
end
